[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
  conditions = {Path = "/:slug"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 